import "./globals.css";
import Navbar from "@/components/Navbar";
import { Geist, Geist_Mono, Inter } from "next/font/google";

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});


const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

//Inter from Google Fonts (instead of localFont)
export const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased bg-orange-50`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
